### ISSUE TITLE
What's new CardDialogflow

### ISSUE THREAD

**Issue by Webbyou** [diegodalbosco/flutter_dialogflow#4]
```
ChatMessage message = new ChatMessage(
      text: response.queryResult.fulfillmentText
 ?? new df.Card()
```
```
new Container(
              margin: const EdgeInsets.only(top: 5.0),
              child: new Text(text?? new df.Card()),
            ),
```
How to display rich messages?
Could You help?

**Comment by diegodalbosco** [comment]
I'm not sure what you are trying to do. Could you describe better the problem?
This package is understood only to detect intent and mapping Dialogflow request/result to objects, there's no ui widgets to display these data, you have to do by your own

**Comment by Webbyou** [comment]
Thank You
